[package]
name="mark2/python"
version="0.0.4"
description="it's Python 3.7!"
license-file="pyodide-0.12.0/LICENSE"
disable-command-rename=true

[[module]]
name="python3.7"
source="bin/python3.7.wasm"
abi = "emscripten"

[[command]]
name="python"
module="python3.7"

[fs]
"lib"="lib"
