[package]
name="python"
version="0.0.0"
description="Python is an interpreted, high-level, general-purpose programming language"
pkg-fs-mount-point="."

[[module]]
name="python3.7"
source="bin/python3.7.wasm"

[[command]]
name="python"
module="python3.7"

[fs]
"lib"="lib"
